// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: agua.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InicializadorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inicializador int32 `protobuf:"varint,1,opt,name=inicializador,proto3" json:"inicializador,omitempty"`
}

func (x *InicializadorRequest) Reset() {
	*x = InicializadorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agua_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InicializadorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicializadorRequest) ProtoMessage() {}

func (x *InicializadorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agua_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicializadorRequest.ProtoReflect.Descriptor instead.
func (*InicializadorRequest) Descriptor() ([]byte, []int) {
	return file_agua_proto_rawDescGZIP(), []int{0}
}

func (x *InicializadorRequest) GetInicializador() int32 {
	if x != nil {
		return x.Inicializador
	}
	return 0
}

type InicializadorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta string `protobuf:"bytes,1,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *InicializadorResponse) Reset() {
	*x = InicializadorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agua_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InicializadorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicializadorResponse) ProtoMessage() {}

func (x *InicializadorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agua_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicializadorResponse.ProtoReflect.Descriptor instead.
func (*InicializadorResponse) Descriptor() ([]byte, []int) {
	return file_agua_proto_rawDescGZIP(), []int{1}
}

func (x *InicializadorResponse) GetRespuesta() string {
	if x != nil {
		return x.Respuesta
	}
	return ""
}

type CoordenadasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archivo string `protobuf:"bytes,1,opt,name=archivo,proto3" json:"archivo,omitempty"` // El contenido del archivo .txt se enviará como una cadena de texto
}

func (x *CoordenadasRequest) Reset() {
	*x = CoordenadasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agua_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordenadasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordenadasRequest) ProtoMessage() {}

func (x *CoordenadasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agua_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordenadasRequest.ProtoReflect.Descriptor instead.
func (*CoordenadasRequest) Descriptor() ([]byte, []int) {
	return file_agua_proto_rawDescGZIP(), []int{2}
}

func (x *CoordenadasRequest) GetArchivo() string {
	if x != nil {
		return x.Archivo
	}
	return ""
}

type CoordenadasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta string `protobuf:"bytes,1,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *CoordenadasResponse) Reset() {
	*x = CoordenadasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agua_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordenadasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordenadasResponse) ProtoMessage() {}

func (x *CoordenadasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agua_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordenadasResponse.ProtoReflect.Descriptor instead.
func (*CoordenadasResponse) Descriptor() ([]byte, []int) {
	return file_agua_proto_rawDescGZIP(), []int{3}
}

func (x *CoordenadasResponse) GetRespuesta() string {
	if x != nil {
		return x.Respuesta
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agua_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agua_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agua_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agua_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agua_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agua_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_agua_proto protoreflect.FileDescriptor

var file_agua_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x67, 0x75, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x14,
	0x49, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x69, 0x6e, 0x69,
	0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x15, 0x49, 0x6e,
	0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x22, 0x2e, 0x0a, 0x12, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x61, 0x64, 0x61, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x6f, 0x22, 0x33, 0x0a, 0x13, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x61, 0x64, 0x61, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e,
	0x73, 0x61, 0x6a, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x32, 0xc8, 0x01, 0x0a, 0x0a, 0x4d, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f,
	0x12, 0x40, 0x0a, 0x0d, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f,
	0x72, 0x12, 0x15, 0x2e, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x49, 0x6e, 0x69, 0x63, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x11, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x65, 0x6e, 0x61, 0x64, 0x61, 0x73, 0x12, 0x13, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x65,
	0x6e, 0x61, 0x64, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x61, 0x64, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x12, 0x11, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6f, 0x67, 0x75, 0x72,
	0x74, 0x68, 0x2f, 0x61, 0x67, 0x75, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agua_proto_rawDescOnce sync.Once
	file_agua_proto_rawDescData = file_agua_proto_rawDesc
)

func file_agua_proto_rawDescGZIP() []byte {
	file_agua_proto_rawDescOnce.Do(func() {
		file_agua_proto_rawDescData = protoimpl.X.CompressGZIP(file_agua_proto_rawDescData)
	})
	return file_agua_proto_rawDescData
}

var file_agua_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agua_proto_goTypes = []interface{}{
	(*InicializadorRequest)(nil),  // 0: InicializadorRequest
	(*InicializadorResponse)(nil), // 1: InicializadorResponse
	(*CoordenadasRequest)(nil),    // 2: CoordenadasRequest
	(*CoordenadasResponse)(nil),   // 3: CoordenadasResponse
	(*HeartbeatRequest)(nil),      // 4: HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 5: HeartbeatResponse
}
var file_agua_proto_depIdxs = []int32{
	0, // 0: MiServicio.Inicializador:input_type -> InicializadorRequest
	2, // 1: MiServicio.EnviarCoordenadas:input_type -> CoordenadasRequest
	4, // 2: MiServicio.Heartbeat:input_type -> HeartbeatRequest
	1, // 3: MiServicio.Inicializador:output_type -> InicializadorResponse
	3, // 4: MiServicio.EnviarCoordenadas:output_type -> CoordenadasResponse
	5, // 5: MiServicio.Heartbeat:output_type -> HeartbeatResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agua_proto_init() }
func file_agua_proto_init() {
	if File_agua_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agua_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InicializadorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agua_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InicializadorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agua_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordenadasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agua_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordenadasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agua_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agua_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agua_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agua_proto_goTypes,
		DependencyIndexes: file_agua_proto_depIdxs,
		MessageInfos:      file_agua_proto_msgTypes,
	}.Build()
	File_agua_proto = out.File
	file_agua_proto_rawDesc = nil
	file_agua_proto_goTypes = nil
	file_agua_proto_depIdxs = nil
}
